version: '3.8'

services:
  backend:
    build: ./backend
    restart: always
    depends_on:
      - db 
    env_file:
      - .env
    environment:
      - PORT=8080
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "8080:8080"
    volumes:
      - ./backend/database/migrations.sql:/app/database/migrations.sql 

  frontend:
    build: ./frontend
    restart: always
    depends_on:
      - backend
    env_file:
      - .env
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:80" 

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=cloudstorage
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5
      start_period: 10s 

volumes:
  pg_data:
